# Generated by Django 5.2.11 on 2026-04-02 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_announcementbar_cproduct_herobanner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cproduct',
            options={},
        ),
        migrations.RemoveField(
            model_name='cproduct',
            name='image',
        ),
        migrations.RemoveField(
            model_name='cproduct',
            name='price',
        ),
        migrations.RemoveField(
            model_name='cproduct',
            name='title',
        ),
        migrations.AddField(
            model_name='cproduct',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collection_items', to='core.product'),
        ),
    ]
